# Generated by Django 3.2.9 on 2021-11-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
